apiVersion: v1
kind: Secret
metadata:
  name: aws-secrets
  namespace: payments
type: Opaque
data:
  aws_access_key_id: QUtJQTRKNlJDQVFUQkdMNk8zUFQ=
  aws_secret_access_key: WmV0S2FlYkxtNFN6OWl2VTkrcE10MnBLdEhFL0gzdG1HaWVLSDEybw==